"""add user_id in table habits

Revision ID: 5dc45b047c78
Revises: 70f3f46e8c07
Create Date: 2024-12-24 18:24:35.533522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc45b047c78'
down_revision: Union[str, None] = '70f3f46e8c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_column('habits', 'user_id')
    # ### end Alembic commands ###
